// Code generated by MockGen. DO NOT EDIT.
// Source: budget_repository.go
//
// Generated by this command:
//
//	mockgen -source=budget_repository.go -destination=mocks/budget_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "raccounting/internal/domain/entity"
	port "raccounting/internal/port"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBudgetRepository is a mock of BudgetRepository interface.
type MockBudgetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBudgetRepositoryMockRecorder
	isgomock struct{}
}

// MockBudgetRepositoryMockRecorder is the mock recorder for MockBudgetRepository.
type MockBudgetRepositoryMockRecorder struct {
	mock *MockBudgetRepository
}

// NewMockBudgetRepository creates a new mock instance.
func NewMockBudgetRepository(ctrl *gomock.Controller) *MockBudgetRepository {
	mock := &MockBudgetRepository{ctrl: ctrl}
	mock.recorder = &MockBudgetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBudgetRepository) EXPECT() *MockBudgetRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockBudgetRepository) List(ctx context.Context) ([]entity.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBudgetRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBudgetRepository)(nil).List), ctx)
}

// Set mocks base method.
func (m *MockBudgetRepository) Set(ctx context.Context, req port.BudgetSetRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockBudgetRepositoryMockRecorder) Set(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockBudgetRepository)(nil).Set), ctx, req)
}
