// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	port "raccounting/internal/port"
	model "raccounting/internal/storage/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CreateTransactionWithBalance mocks base method.
func (m *MockStorage) CreateTransactionWithBalance(ctx context.Context, req port.TransactionCreateRequest) (model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionWithBalance", ctx, req)
	ret0, _ := ret[0].(model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransactionWithBalance indicates an expected call of CreateTransactionWithBalance.
func (mr *MockStorageMockRecorder) CreateTransactionWithBalance(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionWithBalance", reflect.TypeOf((*MockStorage)(nil).CreateTransactionWithBalance), ctx, req)
}

// CreateTransferWithBalance mocks base method.
func (m *MockStorage) CreateTransferWithBalance(ctx context.Context, req port.TransferCreateRequest) (model.Transaction, model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransferWithBalance", ctx, req)
	ret0, _ := ret[0].(model.Transaction)
	ret1, _ := ret[1].(model.Transaction)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateTransferWithBalance indicates an expected call of CreateTransferWithBalance.
func (mr *MockStorageMockRecorder) CreateTransferWithBalance(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransferWithBalance", reflect.TypeOf((*MockStorage)(nil).CreateTransferWithBalance), ctx, req)
}

// DeleteTransactionWithBalance mocks base method.
func (m *MockStorage) DeleteTransactionWithBalance(ctx context.Context, id uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransactionWithBalance", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTransactionWithBalance indicates an expected call of DeleteTransactionWithBalance.
func (mr *MockStorageMockRecorder) DeleteTransactionWithBalance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransactionWithBalance", reflect.TypeOf((*MockStorage)(nil).DeleteTransactionWithBalance), ctx, id)
}

// DeleteTransferWithBalance mocks base method.
func (m *MockStorage) DeleteTransferWithBalance(ctx context.Context, id uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransferWithBalance", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTransferWithBalance indicates an expected call of DeleteTransferWithBalance.
func (mr *MockStorageMockRecorder) DeleteTransferWithBalance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransferWithBalance", reflect.TypeOf((*MockStorage)(nil).DeleteTransferWithBalance), ctx, id)
}

// FindTransactionByID mocks base method.
func (m *MockStorage) FindTransactionByID(ctx context.Context, id uint64) (model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTransactionByID", ctx, id)
	ret0, _ := ret[0].(model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTransactionByID indicates an expected call of FindTransactionByID.
func (mr *MockStorageMockRecorder) FindTransactionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTransactionByID", reflect.TypeOf((*MockStorage)(nil).FindTransactionByID), ctx, id)
}

// ListTransactions mocks base method.
func (m *MockStorage) ListTransactions(ctx context.Context) ([]model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockStorageMockRecorder) ListTransactions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockStorage)(nil).ListTransactions), ctx)
}

// UpdateTransactionWithBalance mocks base method.
func (m *MockStorage) UpdateTransactionWithBalance(ctx context.Context, req port.TransactionUpdateRequest) (model.Transaction, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionWithBalance", ctx, req)
	ret0, _ := ret[0].(model.Transaction)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateTransactionWithBalance indicates an expected call of UpdateTransactionWithBalance.
func (mr *MockStorageMockRecorder) UpdateTransactionWithBalance(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionWithBalance", reflect.TypeOf((*MockStorage)(nil).UpdateTransactionWithBalance), ctx, req)
}
