// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "raccounting/internal/storage/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// ListCategoryBudgets mocks base method.
func (m *MockStorage) ListCategoryBudgets(ctx context.Context) ([]model.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategoryBudgets", ctx)
	ret0, _ := ret[0].([]model.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategoryBudgets indicates an expected call of ListCategoryBudgets.
func (mr *MockStorageMockRecorder) ListCategoryBudgets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategoryBudgets", reflect.TypeOf((*MockStorage)(nil).ListCategoryBudgets), ctx)
}

// SetCategoryBudget mocks base method.
func (m *MockStorage) SetCategoryBudget(ctx context.Context, req model.BudgetSetRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCategoryBudget", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCategoryBudget indicates an expected call of SetCategoryBudget.
func (mr *MockStorageMockRecorder) SetCategoryBudget(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCategoryBudget", reflect.TypeOf((*MockStorage)(nil).SetCategoryBudget), ctx, req)
}
