// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "raccounting/internal/storage/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CreateCurrency mocks base method.
func (m *MockStorage) CreateCurrency(ctx context.Context, req model.CurrencyCreateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCurrency", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCurrency indicates an expected call of CreateCurrency.
func (mr *MockStorageMockRecorder) CreateCurrency(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCurrency", reflect.TypeOf((*MockStorage)(nil).CreateCurrency), ctx, req)
}

// DeleteCurrency mocks base method.
func (m *MockStorage) DeleteCurrency(ctx context.Context, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCurrency", ctx, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCurrency indicates an expected call of DeleteCurrency.
func (mr *MockStorageMockRecorder) DeleteCurrency(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCurrency", reflect.TypeOf((*MockStorage)(nil).DeleteCurrency), ctx, code)
}

// ExistsCurrency mocks base method.
func (m *MockStorage) ExistsCurrency(ctx context.Context, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCurrency", ctx, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCurrency indicates an expected call of ExistsCurrency.
func (mr *MockStorageMockRecorder) ExistsCurrency(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCurrency", reflect.TypeOf((*MockStorage)(nil).ExistsCurrency), ctx, code)
}

// ListCurrencies mocks base method.
func (m *MockStorage) ListCurrencies(ctx context.Context) ([]model.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCurrencies", ctx)
	ret0, _ := ret[0].([]model.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCurrencies indicates an expected call of ListCurrencies.
func (mr *MockStorageMockRecorder) ListCurrencies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCurrencies", reflect.TypeOf((*MockStorage)(nil).ListCurrencies), ctx)
}

// UpdateCurrency mocks base method.
func (m *MockStorage) UpdateCurrency(ctx context.Context, req model.CurrencyUpdateRequest) (model.Currency, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrency", ctx, req)
	ret0, _ := ret[0].(model.Currency)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateCurrency indicates an expected call of UpdateCurrency.
func (mr *MockStorageMockRecorder) UpdateCurrency(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCurrency", reflect.TypeOf((*MockStorage)(nil).UpdateCurrency), ctx, req)
}
